# Generated by Django 5.2.7 on 2025-12-01 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newsletter_approved_by_editor"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="editors",
            field=models.ManyToManyField(
                blank=True, related_name="editor_publisher", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="journalists",
            field=models.ManyToManyField(
                blank=True,
                related_name="publishers_journalists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
